function Hd = bpf_firgaussian
%BPF_FIRGAUSSIAN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
% Generated on: 23-Jul-2014 22:36:43

% FIR Window Bandpass filter designed using the FIR1 function.

% -------------------------------------------------------------------------
% All frequency values are in Hz.
Fs = 360;  % Sampling Frequency
% -------------------------------------------------------------------------

N     = 10;         % Order
Fc1   = 0.09;       % First Cutoff Frequency
Fc2   = 30;         % Second Cutoff Frequency
flag  = 'noscale';  % Sampling Flag
Alpha = 2.5;        % Window Parameter
% Create the window vector for the design algorithm.
win = gausswin(N+1, Alpha);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
